# Generated by Django 4.2.7 on 2026-05-14 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('parent', 'Parent/Guardian'), ('doctor', 'Medical Professional (Doctor/Psychologist)')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1_score', models.IntegerField()),
                ('a2_score', models.IntegerField()),
                ('a3_score', models.IntegerField()),
                ('a4_score', models.IntegerField()),
                ('a5_score', models.IntegerField()),
                ('a6_score', models.IntegerField()),
                ('a7_score', models.IntegerField()),
                ('a8_score', models.IntegerField()),
                ('a9_score', models.IntegerField()),
                ('a10_score', models.IntegerField()),
                ('qchat_10_score', models.IntegerField()),
                ('age', models.FloatField()),
                ('sex', models.CharField(max_length=10)),
                ('ethnicity', models.CharField(max_length=50)),
                ('jaundice', models.CharField(max_length=5)),
                ('family_mem_with_asd', models.CharField(max_length=5)),
                ('speech_delay', models.CharField(max_length=5)),
                ('learning_disorder', models.CharField(max_length=5)),
                ('genetic_disorders', models.CharField(max_length=5)),
                ('depression', models.CharField(max_length=5)),
                ('global_developmental_delay', models.CharField(max_length=5)),
                ('social_behavioural_issues', models.CharField(max_length=5)),
                ('childhood_autism_rating_scale', models.FloatField()),
                ('anxiety_disorder', models.CharField(max_length=5)),
                ('prediction', models.CharField(max_length=5)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
